### ISSUE TITLE
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema

### ISSUE THREAD

**Issue by marcoippolito** [bnsd55/beego-vuejs-starter-kit#3]
I git cloned the repository in my Ubuntu 18.04.01 Server edition.
than when executing yarn && npm run start :+1: 

    marco@pc01:~/vueBooksCode/beego-vuejs-starter-kit$ yarn && npm run start
    yarn install v1.16.0
    warning package-lock.json found. Your project contains lock files generated by tools other than    
    Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies 
    caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
    [1/4] Resolving packages...
    success Already up-to-date.
    Done in 0.41s.

    > beego-vuejs-starter-kit@1.0.0 start /home/marco/vueBooksCode/beego-vuejs-starter-kit
    > cross-env NODE_ENV=development webpack-dev-server --config webpack.dev.config.js

    ✖ ｢wds｣: Invalid configuration object. Webpack has been initialised using a configuration object 
    that does not match the API schema.
     - configuration has an unknown property 'mode'. These properties are valid:
       object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, 
    externals?, loader?, module?, name?, node?, output?, parallelism?, performance?, plugins?,  
    profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, 
    stats?, target?, watch?, watchOptions? }
       For typos: please correct them.
       For loader options: webpack 2 no longer allows custom properties in configuration.
         Loaders should be updated to allow passing options via loader options in module.rules.
         Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the 
    loader:
         plugins: [
           new webpack.LoaderOptionsPlugin({
             // test: /\.xxx$/, // may apply this only for some modules
             options: {
               mode: ...
             }
           })
         ]
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! beego-vuejs-starter-kit@1.0.0 start: `cross-env NODE_ENV=development webpack-   
    dev-server --config webpack.dev.config.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the beego-vuejs-starter-kit@1.0.0 start script.
   npm ERR! This is probably not a problem with npm. There is likely additional logging output 
   above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/marco/.npm/_logs/2019-06-05T12_54_53_095Z-debug.log

And this is the content of the debug.log file:

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
    2 info using npm@6.9.0
    3 info using node@v8.16.0
    4 verbose run-script [ 'prestart', 'start', 'poststart' ]
    5 info lifecycle beego-vuejs-starter-kit@1.0.0~prestart: beego-vuejs-starter-kit@1.0.0
    6 info lifecycle beego-vuejs-starter-kit@1.0.0~start: beego-vuejs-starter-kit@1.0.0
    7 verbose lifecycle beego-vuejs-starter-kit@1.0.0~start: unsafe-perm in lifecycle true
    8 verbose lifecycle beego-vuejs-starter-kit@1.0.0~start: PATH: /usr/lib/node_modules/ 
    npm/node_modules/npm-lifecycle/node-gyp-bin:/home/marco/vueBooksCode/beego-vuejs-  
    starter-kit/node_modules/.bin:/home/m$
    9 verbose lifecycle beego-vuejs-starter-kit@1.0.0~start: CWD: /home/marco/vueBooksCode
    /beego-vuejs-starter-kit
    10 silly lifecycle beego-vuejs-starter-kit@1.0.0~start: Args: [ '-c',
    10 silly lifecycle   'cross-env NODE_ENV=development webpack-dev-server --config 
    webpack.dev.config.js' ]
    11 silly lifecycle beego-vuejs-starter-kit@1.0.0~start: Returned: code: 1  signal: null
    12 info lifecycle beego-vuejs-starter-kit@1.0.0~start: Failed to exec start script
    13 verbose stack Error: beego-vuejs-starter-kit@1.0.0 start: `cross-env    
    NODE_ENV=development webpack-dev-server --config webpack.dev.config.js`
    13 verbose stack Exit status 1
    13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules
    /npm-lifecycle/index.js:301:16)
    13 verbose stack     at emitTwo (events.js:126:13)
    13 verbose stack     at EventEmitter.emit (events.js:214:7)
    13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules
    /npm-lifecycle/lib/spawn.js:55:14)
    13 verbose stack     at emitTwo (events.js:126:13)
    13 verbose stack     at ChildProcess.emit (events.js:214:7)
    13 verbose stack     at maybeClose (internal/child_process.js:915:16)
    13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
    14 verbose pkgid beego-vuejs-starter-kit@1.0.0
    15 verbose cwd /home/marco/vueBooksCode/beego-vuejs-starter-kit
    16 verbose Linux 4.15.0-50-generic
    17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
    18 verbose node v8.16.0
    19 verbose npm  v6.9.0
    20 error code ELIFECYCLE
    21 error errno 1
    22 error beego-vuejs-starter-kit@1.0.0 start: `cross-env NODE_ENV=development webpack-
    dev-server --config webpack.dev.config.js`
    22 error Exit status 1
    23 error Failed at the beego-vuejs-starter-kit@1.0.0 start script.
    23 error This is probably not a problem with npm. There is likely additional logging output 
    above.
    24 verbose exit [ 1, true ]

    npm --version
    6.9.0

    node --version
    v8.16.0

How to solve the problem?
Marco

**Comment by bnsd55** [comment]
Marco,
The problem was an older versions of modules in package.json.
Fix already uploaded, now you can clone and everything will work as expected.

Let me know if you are having some problems :)
